Run non regression tests only if the directory zoidberg_tests exist

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -73,15 +73,17 @@ jobs:
 #          slack_token: ${{ secrets.slack_token }}
       - name: Run zoidberg non regression tests
         run: |
-          if [[ ${{ inputs.pr_deploy }} == true ]]; then
-            output=$(zoidberg -d ./zoidberg_tests -p ${{ inputs.pr }} distance -v)
+          if [ -d "./zoidberg_tests" ]; then
+            if [[ ${{ inputs.pr_deploy }} == true ]]; then
+              output=$(zoidberg -d ./zoidberg_tests -p ${{ inputs.pr }} distance)
             else
-            output=$(zoidberg -d ./zoidberg_tests distance)
-          fi
-          echo "Script Output: $output"
-          if [[ $output != "OK" ]]; then
-            echo "Non regression tests FAILED"
-            exit 1
+              output=$(zoidberg -d ./zoidberg_tests distance)
+            fi
+            echo "Script Output: $output"
+            if [[ $output != "OK" ]]; then
+              echo "Non regression tests FAILED"
+              exit 1
+            fi
           fi
         env:
           WOOSMAP_DEVELOP_API_KEY: ${{ secrets.woosmap_develop_api_key }}
